site_name: whm
# site_url: 站点 URL 链接
site_author: whm
site_description: myblog

nav:
- Home: index.md
- Python:
    - 数据结构:
      - 数值型: python/structure/number.md
      - 序列: python/structure/sequence.md
      - 字典和集合: python/structure/dict&set.md
      - 可变/不可变类型: python/structure/mutable&immutable.md
      - 二叉树: python/structure/binary_tree.md
    - 闭包&装饰器&柯里化: python/closure.md
    - 正则表达式: python/regex/re.md
    - pytest:
      - 测试夹具: python/pytest/fixture.md
      - pytest.main: python/pytest/pytest.main.md
      - pytest.ini: python/pytest/pytest.ini.md
    - app自动化:
        - airtest: python/app/mumu_sim.md
        - appium: python/app/appium.md
    - unittest笔记: python/unittest/unittest_notes.md
    - selenium笔记: python/selenium/selenium_notes.md
    - pydocx笔记: python/pydocx/pydocx_notes.md
    - pyjson笔记: python/pyjson/pyjson_notes.md
    - OJ:
        - 动态规划: python/oj/dp.md
    - 其他:
      - Python路径迁移: python/other/mv_py_path.md
      - mkdocs使用记录: python/other/mkdocs_notes.md
      - 爬虫入门笔记: python/other/scrapy_notes.md
- 数据库:
    - Oracle:
      - sqlldr导入大量数据: sql/oracle/sqlldr_import.md
      - 分区&同义词&序列: sql/oracle/some.md
      - 查询锁表&解锁: sql/oracle/lock&unlock.md
      - 存储过程: sql/oracle/procedure.md
      - 收集表统计信息: sql/oracle/gather_table_stats.md
      - 其他笔记: sql/oracle/other_notes.md
    - Redis笔记: sql/redis_notes.md
- Shell:
    - regex.sh: shell/regex.md
    - 检查命令耗时: shell/timestamp.md
- 测试工具:
    - Fiddler: utils/fiddler_notes.md
    - Charles: utils/charles_notes.md
    - Postman: utils/postman_notes.md
- Hadoop:
  - Hadoop生态: hadoop/ecosystem.md
  - Scala:
      - Day01: hadoop/scala/day01.md
      - Day02: hadoop/scala/day02.md
      - Day03: hadoop/scala/day03.md
      - Day04: hadoop/scala/day04.md
- Docker:
    - Docker for Windows: docker/windows_docker.md
    - 构建MySQL镜像: docker/build_mysql.md
    - 构建Oracle镜像: docker/build_oracle.md
    #  - 构建Jenkins镜像: docker/build_jenkins.md
- 其他:
    - Nginx笔记: other/nginx_notes.md

# 搜索栏右侧git链接
repo_url: https://github.com/Jork-S-B/Jork-S-B.github.io/tree/main
repo_name: 'myblog'

theme:
    # favicon: logo.png  # 网站logo，默认从./docs/logo.png读取
    icon:
        logo: fontawesome/solid/face-smile-wink  # site_name左侧图标
        repo: fontawesome/brands/git-alt  # git链接图标
    name: 'material'  # 设置mkdocs-material主题，需要先pip install mkdocs-material
    language: zh
    features:
        - navigation.footer  # 设置上一页和下一页
        - navigation.top  # 一键回顶部
        - navigation.tabs  # 顶部显示导航顶层nav
        - navigation.instant  # 点击内部链接时，不用全部刷新页面
        # - navigation.path  # 展示当前文档路径
        - content.code.copy  # 代码块复制按钮
    palette:
        # 切换样式方案及按钮
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: teal
          toggle:
            icon: material/lightbulb
            name: 切换至深色模式

        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          toggle:
            icon: material/lightbulb-outline
            name: 切换至浅色模式

extra_css:
  - stylesheets/extra.css  # 自定义css文件

markdown_extensions:
    # emoji等图标的扩展
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    # 可切换tab页的代码块扩展
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    # 提示框扩展
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    # 表格扩展
    - tables
    # 支持markdown任务列表的插件
    - pymdownx.tasklist:
        custom_checkbox: true

plugins:
    # 图片放大插件，需要先pip install mkdocs-glightbox
    - glightbox
    # 中文搜索插件，需要pip install jieba
    - search:
        # 正则表达式，\s 匹配任何空白字符，包括空格、制表符、换行符等；\u200b 不可视的特殊占位符，文本渲染时用到，此处实测对搜索结果挺大
        separator: '[\s+\u200b\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
        lang:
          - en
          - zh
    # 显示文件最后修改时间插件，需要先pip install mkdocs-git-revision-date-localized-plugin
    # 参考资料：https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/
    - git-revision-date-localized:
        timezone: Asia/Shanghai
        type: iso_datetime
        # fallback_to_build_date: true  # mkdocs build的日期
        enable_creation_date: false
        exclude:  # 以下文件/目录排除
          - index.md